apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
  namespace: homework
spec:
  initContainers:
    - name: init-webpage
      image: busybox
      command: ["sh", "-c", 'echo "Welcome to our website!" > /init/index.html']
      volumeMounts:
        - name: workdir
          mountPath: /init
  containers:
    - name: nginx-container
      image: nginx
      command: ["sh", "-c", "cat /homework/index.html; tail -f /dev/null"]
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "100m"
          memory: "256Mi"
      volumeMounts:
        - name: workdir
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command: ["sh", "-c", "rm -f /homework/index.html"]
      ports:
        - containerPort: 8000
  volumes:
    - name: workdir
      emptyDir: {}
